### ISSUE TITLE
Add more channel types

### ISSUE THREAD

**Issue by MoKhajavi75** [Hr-ArshA/Educational-YouTube-Fa#6]
Hey

I suggest to rename repo to `awesome-persian-educations` and try to cover telegram channels too!

**Comment by shahriaarrr** [comment]
> Hey
> 
> I suggest to rename repo to `awesome-persian-educations` and try to cover telegram channels too!

that's good suggestion @MohamadKh75 
but this repo just for YouTube channels and not for telegram channels or websites and ....
